// Older saved turns can contain a source list generated by the model. The UI owns that list.
export function displayAnswer(text) {
  return String(text || '').replace(/\n(?:#{1,6}\s*Sources(?: consulted)?|\*\*Sources(?: consulted)?\*\*|Sources(?: consulted)?):?\s*\n(?:\s*(?:[-*+]\s+|\d+\.\s+).+\n?)+\s*$/i, '').trimEnd();
}
