/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Migration = {
  sourceKey?: string;
  sourceHash?: string;
  importHash?: string;
  snapshotAt?: string;
  qualityIssues?: Array<string>;
};

export type AnalysisSettings = {
  _id: string;
  _type: "analysisSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  texts?: Array<{
    key?: string;
    title?: string;
    text?: string;
    _type: "promptText";
    _key: string;
  }>;
  questions?: Array<{
    key?: string;
    type?: string;
    instructions?: string;
    criteria?: Array<string>;
    options?: Array<{
      key?: string;
      text?: string;
      _type: "jevOption";
      _key: string;
    }>;
    _type: "jevQuestion";
    _key: string;
  }>;
  dimensions?: Array<{
    id?: string;
    label?: string;
    weight?: number;
    gap?: string;
    _type: "fitDimension";
    _key: string;
  }>;
  facts?: Array<{
    question?: string;
    answer?: string;
    _type: "factualAnswer";
    _key: string;
  }>;
  routineQuestions?: Array<string>;
  personalFacts?: {
    availability?: string;
    location?: string;
    sponsorship?: string;
  };
};

export type MigrationRecord = {
  _id: string;
  _type: "migrationRecord";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  kind?: string;
  payload?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type WritingGuidance = {
  _id: string;
  _type: "writingGuidance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  scope?:
    | "shared"
    | "analysis"
    | "cover"
    | "answer"
    | "research"
    | "brief"
    | "assessment";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  reviewedAt?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type CandidateProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "candidateProfile";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SitePage = {
  _id: string;
  _type: "sitePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  candidate?: CandidateProfileReference;
  download?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  legacyPath?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type JobReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "job";
};

export type ApplicationQuestion = {
  _id: string;
  _type: "applicationQuestion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  job?: JobReference;
  question?: string;
  answer?: string;
  wordLimit?: number;
  refused?: boolean;
  reason?: string;
  answeredAt?: string;
  order?: number;
  migration?: Migration;
  sourcePayload?: string;
};

export type FitReportReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "fitReport";
};

export type CoverLetterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coverLetter";
};

export type CompanyResearchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "companyResearch";
};

export type InterviewBriefReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "interviewBrief";
};

export type FitAssessmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "fitAssessment";
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  company?: string;
  role?: string;
  jobDescription?: string;
  location?: string;
  locationMode?: string;
  salary?: string;
  source?: string;
  sourceType?: string;
  sourceUrl?: string;
  externalId?: string;
  threadId?: string;
  stage?:
    | "new"
    | "reviewing"
    | "applied"
    | "interviewing"
    | "offer"
    | "rejected"
    | "not_interested"
    | "expired";
  archived?: boolean;
  archivedAt?: string;
  notes?: string;
  instructions?: string;
  recruiter?: {
    name?: string;
    org?: string;
    company?: string;
    email?: string;
    phone?: string;
    daysWaiting?: number;
    receivedAt?: string;
  };
  rationale?: string;
  overviewSummary?: {
    position?: string;
    fit?: string;
    model?: string;
    policy?: string;
    fingerprint?: string;
    assessedAt?: string;
    generatedAt?: string;
  };
  candidate?: CandidateProfileReference;
  activeReport?: FitReportReference;
  activeCoverLetter?: CoverLetterReference;
  activeResearch?: CompanyResearchReference;
  activeBrief?: InterviewBriefReference;
  activeAssessment?: FitAssessmentReference;
  receivedAt?: string;
  createdAt?: string;
  replyOwed?: boolean;
  userViewed?: boolean;
  closed?: boolean;
  score?: number;
  tier?: string;
  updatedAt?: string;
  sourceRevision?: number;
  migration?: Migration;
  sourcePayload?: string;
};

export type FitAssessment = {
  _id: string;
  _type: "fitAssessment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  versionId?: string;
  generatedAt?: string;
  model?: string;
  versionInstructions?: string;
  job?: JobReference;
  score?: number;
  dimensions?: Array<{
    id?: string;
    label?: string;
    weight?: number;
    score?: number;
    confidence?: number;
    probabilities?: Array<{
      label?: string;
      value?: number;
      _key: string;
    }>;
    evidenceProbability?: number;
    evidenceLimited?: boolean;
    evidenceNote?: string;
    _key: string;
  }>;
  reasoning?: string;
  clarifications?: string;
  inputFingerprint?: string;
  policyVersion?: string;
  posting?: {
    type?: string;
    choice?: string;
    confidence?: number;
    probabilities?: Array<{
      label?: string;
      value?: number;
      _key: string;
    }>;
  };
  constraint?: {
    type?: string;
    choice?: string;
    confidence?: number;
    probabilities?: Array<{
      label?: string;
      value?: number;
      _key: string;
    }>;
  };
  blocked?: boolean;
  provisional?: boolean;
  status?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type InterviewBrief = {
  _id: string;
  _type: "interviewBrief";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  versionId?: string;
  generatedAt?: string;
  model?: string;
  versionInstructions?: string;
  job?: JobReference;
  research?: CompanyResearchReference;
  contact?: string;
  opening?: string;
  why?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  conversationNotes?: string;
  conversation?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  likelyQuestions?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  gapResponses?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  greenFlags?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  redFlags?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  questionsToAsk?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  companyReference?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  roleReference?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  personalAnswers?: {
    advertisedSalary?: string;
    personallyExpectedSalary?: string;
    previouslyDiscussedSalary?: string;
    availability?: string;
    location?: string;
    locationMode?: string;
    noticePeriod?: string;
    startDate?: string;
    sponsorship?: string;
  };
  confirmedAnswers?: Array<{
    question?: string;
    answer?: string;
    answeredAt?: string;
    _key: string;
  }>;
  unknowns?: Array<string>;
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  company?: string;
  role?: string;
  stage?: string;
  conversationReceivedAt?: string;
  conversationUpdatedAt?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type CompanyResearch = {
  _id: string;
  _type: "companyResearch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  versionId?: string;
  generatedAt?: string;
  model?: string;
  versionInstructions?: string;
  job?: JobReference;
  company?: string;
  domain?: string;
  summary?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  signals?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  risks?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  roleContext?: Array<
    {
      _key: string;
    } & EvidencePoint
  >;
  unknowns?: Array<string>;
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  partial?: boolean;
  migration?: Migration;
  sourcePayload?: string;
};

export type CoverLetter = {
  _id: string;
  _type: "coverLetter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  versionId?: string;
  generatedAt?: string;
  model?: string;
  versionInstructions?: string;
  job?: JobReference;
  salutation?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  wordCount?: number;
  migration?: Migration;
  sourcePayload?: string;
};

export type FitReport = {
  _id: string;
  _type: "fitReport";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  versionId?: string;
  generatedAt?: string;
  model?: string;
  versionInstructions?: string;
  job?: JobReference;
  jobTitle?: string;
  company?: string;
  jobDescription?: string;
  pitch?: string;
  categories?: Array<{
    name?: string;
    note?: string;
    _type: "fitCategory";
    _key: string;
  }>;
  differentiators?: Array<{
    headline?: string;
    detail?: string;
    _type: "differentiator";
    _key: string;
  }>;
  closing?: string;
  privateReasoning?: string;
  publiclyShared?: boolean;
  jobs?: Array<
    {
      _key: string;
    } & JobReference
  >;
  active?: boolean;
  createdAt?: string;
  regeneratedAt?: string;
  generation?: {
    prompt?: string;
    instructions?: string;
    effort?: string;
  };
  internalAssessment?: {
    score?: number;
    tier?: string;
    reasoning?: string;
    breakdown?: Array<{
      label?: string;
      value?: number;
      _key: string;
    }>;
  };
  migration?: Migration;
  sourcePayload?: string;
};

export type CandidateEvidence = {
  _id: string;
  _type: "candidateEvidence";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  kind?:
    | "employment"
    | "achievement"
    | "project"
    | "education"
    | "skill"
    | "preference"
    | "fact";
  organisation?: string;
  period?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  sources?: Array<
    {
      _key: string;
    } & Source
  >;
  reviewedAt?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type CandidateEvidenceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "candidateEvidence";
};

export type CandidateProfile = {
  _id: string;
  _type: "candidateProfile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  summary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  motivationSummary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  interviewSummary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  location?: string;
  availability?: string;
  workEligibility?: string;
  noticePeriod?: string;
  careerDirection?: string;
  workingPreferences?: string;
  salaryPreferences?: string;
  constraints?: string;
  evidence?: Array<
    {
      _key: string;
    } & CandidateEvidenceReference
  >;
  confirmedAnswers?: Array<{
    question?: string;
    answer?: string;
    _type: "confirmedAnswer";
    _key: string;
  }>;
  reviewedAt?: string;
  migration?: Migration;
  sourcePayload?: string;
};

export type EvidencePoint = {
  _type: "evidencePoint";
  text?: string;
  sourceKey?: string;
  basis?: "research" | "posting" | "judgement";
};

export type Source = {
  _type: "source";
  title?: string;
  url?: string;
  publishedAt?: string;
  retrievedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Migration
  | AnalysisSettings
  | MigrationRecord
  | WritingGuidance
  | CandidateProfileReference
  | SanityFileAssetReference
  | SitePage
  | Slug
  | JobReference
  | ApplicationQuestion
  | FitReportReference
  | CoverLetterReference
  | CompanyResearchReference
  | InterviewBriefReference
  | FitAssessmentReference
  | Job
  | FitAssessment
  | InterviewBrief
  | CompanyResearch
  | CoverLetter
  | FitReport
  | CandidateEvidence
  | CandidateEvidenceReference
  | CandidateProfile
  | EvidencePoint
  | Source
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../fit-app/lib/sanity/analysis-settings.js
// Variable: ANALYSIS_SETTINGS_QUERY
// Query: *[_type == "analysisSettings" && _id == "fit-analysis-settings"][0]{  _id, _rev, texts[]{key, text}, questions[]{key, type, instructions, criteria, options[]{key, text}},  dimensions[]{id, label, weight, gap}, facts[]{question, answer}, routineQuestions,  personalFacts{availability, location, sponsorship}}
export type ANALYSIS_SETTINGS_QUERY_RESULT = {
  _id: "fit-analysis-settings";
  _rev: string;
  texts: Array<{
    key: string | null;
    text: string | null;
  }> | null;
  questions: Array<{
    key: string | null;
    type: string | null;
    instructions: string | null;
    criteria: Array<string> | null;
    options: Array<{
      key: string | null;
      text: string | null;
    }> | null;
  }> | null;
  dimensions: Array<{
    id: string | null;
    label: string | null;
    weight: number | null;
    gap: string | null;
  }> | null;
  facts: Array<{
    question: string | null;
    answer: string | null;
  }> | null;
  routineQuestions: Array<string> | null;
  personalFacts: {
    availability: string | null;
    location: string | null;
    sponsorship: string | null;
  } | null;
} | null;

// Source: ../fit-app/lib/sanity/queries.js
// Variable: CONTENT_COUNTS_QUERY
// Query: {  "analysisSettings": count(*[_type == "analysisSettings"]),  "candidateProfile": count(*[_type == "candidateProfile"]),  "candidateEvidence": count(*[_type == "candidateEvidence"]),  "job": count(*[_type == "job"]),  "applicationQuestion": count(*[_type == "applicationQuestion"]),  "fitReport": count(*[_type == "fitReport"]),  "coverLetter": count(*[_type == "coverLetter"]),  "companyResearch": count(*[_type == "companyResearch"]),  "interviewBrief": count(*[_type == "interviewBrief"]),  "fitAssessment": count(*[_type == "fitAssessment"]),  "sitePage": count(*[_type == "sitePage"]),  "writingGuidance": count(*[_type == "writingGuidance"])}
export type CONTENT_COUNTS_QUERY_RESULT = {
  analysisSettings: number;
  candidateProfile: number;
  candidateEvidence: number;
  job: number;
  applicationQuestion: number;
  fitReport: number;
  coverLetter: number;
  companyResearch: number;
  interviewBrief: number;
  fitAssessment: number;
  sitePage: number;
  writingGuidance: number;
};

// Source: ../fit-app/lib/sanity/queries.js
// Variable: CANDIDATE_QUERY
// Query: *[_type == "candidateProfile" && _id == $id][0]{  _id, _rev, name, headline, summary, motivationSummary, interviewSummary,  location, availability, workEligibility, noticePeriod, careerDirection,  workingPreferences, salaryPreferences, constraints, confirmedAnswers, reviewedAt,  evidence[]->{_id, _rev, title, kind, organisation, period, body, sources, reviewedAt}}
export type CANDIDATE_QUERY_RESULT = {
  _id: string;
  _rev: string;
  name: string | null;
  headline: string | null;
  summary: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  motivationSummary: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  interviewSummary: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  location: string | null;
  availability: string | null;
  workEligibility: string | null;
  noticePeriod: string | null;
  careerDirection: string | null;
  workingPreferences: string | null;
  salaryPreferences: string | null;
  constraints: string | null;
  confirmedAnswers: Array<{
    question?: string;
    answer?: string;
    _type: "confirmedAnswer";
    _key: string;
  }> | null;
  reviewedAt: string | null;
  evidence: Array<{
    _id: string;
    _rev: string;
    title: string | null;
    kind:
      | "achievement"
      | "education"
      | "employment"
      | "fact"
      | "preference"
      | "project"
      | "skill"
      | null;
    organisation: string | null;
    period: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    sources: Array<
      {
        _key: string;
      } & Source
    > | null;
    reviewedAt: string | null;
  }> | null;
} | null;

// Source: ../fit-app/lib/sanity/queries.js
// Variable: JOB_CONTENT_QUERY
// Query: *[_type == "job" && _id == $id][0]{  ...,  candidate->{_id, name}, activeReport->, activeCoverLetter->, activeResearch->,  activeBrief->, activeAssessment->,  "questions": *[_type == "applicationQuestion" && job._ref == ^._id] | order(order asc, _createdAt asc),  "reportVersions": *[_type == "fitReport" && (job._ref == ^._id || ^._id in jobs[]._ref)] | order(generatedAt desc){_id, versionId, generatedAt, model, active},  "coverVersions": *[_type == "coverLetter" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model},  "researchVersions": *[_type == "companyResearch" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model},  "briefVersions": *[_type == "interviewBrief" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model}}
export type JOB_CONTENT_QUERY_RESULT = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legacyId?: string;
  company?: string;
  role?: string;
  jobDescription?: string;
  location?: string;
  locationMode?: string;
  salary?: string;
  source?: string;
  sourceType?: string;
  sourceUrl?: string;
  externalId?: string;
  threadId?: string;
  stage?:
    | "applied"
    | "expired"
    | "interviewing"
    | "new"
    | "not_interested"
    | "offer"
    | "rejected"
    | "reviewing";
  archived?: boolean;
  archivedAt?: string;
  notes?: string;
  instructions?: string;
  recruiter?: {
    name?: string;
    org?: string;
    company?: string;
    email?: string;
    phone?: string;
    daysWaiting?: number;
    receivedAt?: string;
  };
  rationale?: string;
  overviewSummary?: {
    position?: string;
    fit?: string;
    model?: string;
    policy?: string;
    fingerprint?: string;
    assessedAt?: string;
    generatedAt?: string;
  };
  candidate: {
    _id: string;
    name: string | null;
  } | null;
  activeReport: {
    _id: string;
    _type: "fitReport";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    versionId?: string;
    generatedAt?: string;
    model?: string;
    versionInstructions?: string;
    job?: JobReference;
    jobTitle?: string;
    company?: string;
    jobDescription?: string;
    pitch?: string;
    categories?: Array<{
      name?: string;
      note?: string;
      _type: "fitCategory";
      _key: string;
    }>;
    differentiators?: Array<{
      headline?: string;
      detail?: string;
      _type: "differentiator";
      _key: string;
    }>;
    closing?: string;
    privateReasoning?: string;
    publiclyShared?: boolean;
    jobs?: Array<
      {
        _key: string;
      } & JobReference
    >;
    active?: boolean;
    createdAt?: string;
    regeneratedAt?: string;
    generation?: {
      prompt?: string;
      instructions?: string;
      effort?: string;
    };
    internalAssessment?: {
      score?: number;
      tier?: string;
      reasoning?: string;
      breakdown?: Array<{
        label?: string;
        value?: number;
        _key: string;
      }>;
    };
    migration?: Migration;
    sourcePayload?: string;
  } | null;
  activeCoverLetter: {
    _id: string;
    _type: "coverLetter";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    versionId?: string;
    generatedAt?: string;
    model?: string;
    versionInstructions?: string;
    job?: JobReference;
    salutation?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    wordCount?: number;
    migration?: Migration;
    sourcePayload?: string;
  } | null;
  activeResearch: {
    _id: string;
    _type: "companyResearch";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    versionId?: string;
    generatedAt?: string;
    model?: string;
    versionInstructions?: string;
    job?: JobReference;
    company?: string;
    domain?: string;
    summary?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    signals?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    risks?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    roleContext?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    unknowns?: Array<string>;
    sources?: Array<
      {
        _key: string;
      } & Source
    >;
    partial?: boolean;
    migration?: Migration;
    sourcePayload?: string;
  } | null;
  activeBrief: {
    _id: string;
    _type: "interviewBrief";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    versionId?: string;
    generatedAt?: string;
    model?: string;
    versionInstructions?: string;
    job?: JobReference;
    research?: CompanyResearchReference;
    contact?: string;
    opening?: string;
    why?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    conversationNotes?: string;
    conversation?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    likelyQuestions?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    gapResponses?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    greenFlags?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    redFlags?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    questionsToAsk?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    companyReference?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    roleReference?: Array<
      {
        _key: string;
      } & EvidencePoint
    >;
    personalAnswers?: {
      advertisedSalary?: string;
      personallyExpectedSalary?: string;
      previouslyDiscussedSalary?: string;
      availability?: string;
      location?: string;
      locationMode?: string;
      noticePeriod?: string;
      startDate?: string;
      sponsorship?: string;
    };
    confirmedAnswers?: Array<{
      question?: string;
      answer?: string;
      answeredAt?: string;
      _key: string;
    }>;
    unknowns?: Array<string>;
    sources?: Array<
      {
        _key: string;
      } & Source
    >;
    company?: string;
    role?: string;
    stage?: string;
    conversationReceivedAt?: string;
    conversationUpdatedAt?: string;
    migration?: Migration;
    sourcePayload?: string;
  } | null;
  activeAssessment: {
    _id: string;
    _type: "fitAssessment";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    versionId?: string;
    generatedAt?: string;
    model?: string;
    versionInstructions?: string;
    job?: JobReference;
    score?: number;
    dimensions?: Array<{
      id?: string;
      label?: string;
      weight?: number;
      score?: number;
      confidence?: number;
      probabilities?: Array<{
        label?: string;
        value?: number;
        _key: string;
      }>;
      evidenceProbability?: number;
      evidenceLimited?: boolean;
      evidenceNote?: string;
      _key: string;
    }>;
    reasoning?: string;
    clarifications?: string;
    inputFingerprint?: string;
    policyVersion?: string;
    posting?: {
      type?: string;
      choice?: string;
      confidence?: number;
      probabilities?: Array<{
        label?: string;
        value?: number;
        _key: string;
      }>;
    };
    constraint?: {
      type?: string;
      choice?: string;
      confidence?: number;
      probabilities?: Array<{
        label?: string;
        value?: number;
        _key: string;
      }>;
    };
    blocked?: boolean;
    provisional?: boolean;
    status?: string;
    migration?: Migration;
    sourcePayload?: string;
  } | null;
  receivedAt?: string;
  createdAt?: string;
  replyOwed?: boolean;
  userViewed?: boolean;
  closed?: boolean;
  score?: number;
  tier?: string;
  updatedAt?: string;
  sourceRevision?: number;
  migration?: Migration;
  sourcePayload?: string;
  questions: Array<{
    _id: string;
    _type: "applicationQuestion";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    legacyId?: string;
    job?: JobReference;
    question?: string;
    answer?: string;
    wordLimit?: number;
    refused?: boolean;
    reason?: string;
    answeredAt?: string;
    order?: number;
    migration?: Migration;
    sourcePayload?: string;
  }>;
  reportVersions: Array<{
    _id: string;
    versionId: string | null;
    generatedAt: string | null;
    model: string | null;
    active: boolean | null;
  }>;
  coverVersions: Array<{
    _id: string;
    versionId: string | null;
    generatedAt: string | null;
    model: string | null;
  }>;
  researchVersions: Array<{
    _id: string;
    versionId: string | null;
    generatedAt: string | null;
    model: string | null;
  }>;
  briefVersions: Array<{
    _id: string;
    versionId: string | null;
    generatedAt: string | null;
    model: string | null;
  }>;
} | null;

// Source: ../fit-app/lib/sanity/queries.js
// Variable: CONTENT_LIST_QUERY
// Query: *[_type == $type] | order(_updatedAt desc, _id asc)[$start...$end]{  _id, _type, _rev, _updatedAt, title, name, role, company, question, headline, stage,  "slug": slug.current}
export type CONTENT_LIST_QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "analysisSettings";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "applicationQuestion";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: null;
      company: null;
      question: string | null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "candidateEvidence";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "candidateProfile";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: string | null;
      role: null;
      company: null;
      question: null;
      headline: string | null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "companyResearch";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: null;
      company: string | null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "coverLetter";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "fitAssessment";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "fitReport";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: null;
      company: string | null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "interviewBrief";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: string | null;
      company: string | null;
      question: null;
      headline: null;
      stage: string | null;
      slug: null;
    }
  | {
      _id: string;
      _type: "job";
      _rev: string;
      _updatedAt: string;
      title: null;
      name: null;
      role: string | null;
      company: string | null;
      question: null;
      headline: null;
      stage:
        | "applied"
        | "expired"
        | "interviewing"
        | "new"
        | "not_interested"
        | "offer"
        | "rejected"
        | "reviewing"
        | null;
      slug: null;
    }
  | {
      _id: string;
      _type: "migrationRecord";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
  | {
      _id: string;
      _type: "sitePage";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: string | null;
    }
  | {
      _id: string;
      _type: "writingGuidance";
      _rev: string;
      _updatedAt: string;
      title: string | null;
      name: null;
      role: null;
      company: null;
      question: null;
      headline: null;
      stage: null;
      slug: null;
    }
>;

// Source: ../fit-app/lib/sanity/queries.js
// Variable: CONTENT_DOCUMENT_QUERY
// Query: *[_type == $type && _id == $id][0]
export type CONTENT_DOCUMENT_QUERY_RESULT =
  | {
      _id: string;
      _type: "analysisSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      texts?: Array<{
        key?: string;
        title?: string;
        text?: string;
        _type: "promptText";
        _key: string;
      }>;
      questions?: Array<{
        key?: string;
        type?: string;
        instructions?: string;
        criteria?: Array<string>;
        options?: Array<{
          key?: string;
          text?: string;
          _type: "jevOption";
          _key: string;
        }>;
        _type: "jevQuestion";
        _key: string;
      }>;
      dimensions?: Array<{
        id?: string;
        label?: string;
        weight?: number;
        gap?: string;
        _type: "fitDimension";
        _key: string;
      }>;
      facts?: Array<{
        question?: string;
        answer?: string;
        _type: "factualAnswer";
        _key: string;
      }>;
      routineQuestions?: Array<string>;
      personalFacts?: {
        availability?: string;
        location?: string;
        sponsorship?: string;
      };
    }
  | {
      _id: string;
      _type: "applicationQuestion";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      job?: JobReference;
      question?: string;
      answer?: string;
      wordLimit?: number;
      refused?: boolean;
      reason?: string;
      answeredAt?: string;
      order?: number;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "candidateEvidence";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      kind?:
        | "achievement"
        | "education"
        | "employment"
        | "fact"
        | "preference"
        | "project"
        | "skill";
      organisation?: string;
      period?: string;
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      sources?: Array<
        {
          _key: string;
        } & Source
      >;
      reviewedAt?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "candidateProfile";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      headline?: string;
      summary?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      motivationSummary?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      interviewSummary?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      location?: string;
      availability?: string;
      workEligibility?: string;
      noticePeriod?: string;
      careerDirection?: string;
      workingPreferences?: string;
      salaryPreferences?: string;
      constraints?: string;
      evidence?: Array<
        {
          _key: string;
        } & CandidateEvidenceReference
      >;
      confirmedAnswers?: Array<{
        question?: string;
        answer?: string;
        _type: "confirmedAnswer";
        _key: string;
      }>;
      reviewedAt?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "companyResearch";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      versionId?: string;
      generatedAt?: string;
      model?: string;
      versionInstructions?: string;
      job?: JobReference;
      company?: string;
      domain?: string;
      summary?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      signals?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      risks?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      roleContext?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      unknowns?: Array<string>;
      sources?: Array<
        {
          _key: string;
        } & Source
      >;
      partial?: boolean;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "coverLetter";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      versionId?: string;
      generatedAt?: string;
      model?: string;
      versionInstructions?: string;
      job?: JobReference;
      salutation?: string;
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      wordCount?: number;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "fitAssessment";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      versionId?: string;
      generatedAt?: string;
      model?: string;
      versionInstructions?: string;
      job?: JobReference;
      score?: number;
      dimensions?: Array<{
        id?: string;
        label?: string;
        weight?: number;
        score?: number;
        confidence?: number;
        probabilities?: Array<{
          label?: string;
          value?: number;
          _key: string;
        }>;
        evidenceProbability?: number;
        evidenceLimited?: boolean;
        evidenceNote?: string;
        _key: string;
      }>;
      reasoning?: string;
      clarifications?: string;
      inputFingerprint?: string;
      policyVersion?: string;
      posting?: {
        type?: string;
        choice?: string;
        confidence?: number;
        probabilities?: Array<{
          label?: string;
          value?: number;
          _key: string;
        }>;
      };
      constraint?: {
        type?: string;
        choice?: string;
        confidence?: number;
        probabilities?: Array<{
          label?: string;
          value?: number;
          _key: string;
        }>;
      };
      blocked?: boolean;
      provisional?: boolean;
      status?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "fitReport";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      versionId?: string;
      generatedAt?: string;
      model?: string;
      versionInstructions?: string;
      job?: JobReference;
      jobTitle?: string;
      company?: string;
      jobDescription?: string;
      pitch?: string;
      categories?: Array<{
        name?: string;
        note?: string;
        _type: "fitCategory";
        _key: string;
      }>;
      differentiators?: Array<{
        headline?: string;
        detail?: string;
        _type: "differentiator";
        _key: string;
      }>;
      closing?: string;
      privateReasoning?: string;
      publiclyShared?: boolean;
      jobs?: Array<
        {
          _key: string;
        } & JobReference
      >;
      active?: boolean;
      createdAt?: string;
      regeneratedAt?: string;
      generation?: {
        prompt?: string;
        instructions?: string;
        effort?: string;
      };
      internalAssessment?: {
        score?: number;
        tier?: string;
        reasoning?: string;
        breakdown?: Array<{
          label?: string;
          value?: number;
          _key: string;
        }>;
      };
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "interviewBrief";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      versionId?: string;
      generatedAt?: string;
      model?: string;
      versionInstructions?: string;
      job?: JobReference;
      research?: CompanyResearchReference;
      contact?: string;
      opening?: string;
      why?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      conversationNotes?: string;
      conversation?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      likelyQuestions?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      gapResponses?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      greenFlags?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      redFlags?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      questionsToAsk?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      companyReference?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      roleReference?: Array<
        {
          _key: string;
        } & EvidencePoint
      >;
      personalAnswers?: {
        advertisedSalary?: string;
        personallyExpectedSalary?: string;
        previouslyDiscussedSalary?: string;
        availability?: string;
        location?: string;
        locationMode?: string;
        noticePeriod?: string;
        startDate?: string;
        sponsorship?: string;
      };
      confirmedAnswers?: Array<{
        question?: string;
        answer?: string;
        answeredAt?: string;
        _key: string;
      }>;
      unknowns?: Array<string>;
      sources?: Array<
        {
          _key: string;
        } & Source
      >;
      company?: string;
      role?: string;
      stage?: string;
      conversationReceivedAt?: string;
      conversationUpdatedAt?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "job";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      legacyId?: string;
      company?: string;
      role?: string;
      jobDescription?: string;
      location?: string;
      locationMode?: string;
      salary?: string;
      source?: string;
      sourceType?: string;
      sourceUrl?: string;
      externalId?: string;
      threadId?: string;
      stage?:
        | "applied"
        | "expired"
        | "interviewing"
        | "new"
        | "not_interested"
        | "offer"
        | "rejected"
        | "reviewing";
      archived?: boolean;
      archivedAt?: string;
      notes?: string;
      instructions?: string;
      recruiter?: {
        name?: string;
        org?: string;
        company?: string;
        email?: string;
        phone?: string;
        daysWaiting?: number;
        receivedAt?: string;
      };
      rationale?: string;
      overviewSummary?: {
        position?: string;
        fit?: string;
        model?: string;
        policy?: string;
        fingerprint?: string;
        assessedAt?: string;
        generatedAt?: string;
      };
      candidate?: CandidateProfileReference;
      activeReport?: FitReportReference;
      activeCoverLetter?: CoverLetterReference;
      activeResearch?: CompanyResearchReference;
      activeBrief?: InterviewBriefReference;
      activeAssessment?: FitAssessmentReference;
      receivedAt?: string;
      createdAt?: string;
      replyOwed?: boolean;
      userViewed?: boolean;
      closed?: boolean;
      score?: number;
      tier?: string;
      updatedAt?: string;
      sourceRevision?: number;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "migrationRecord";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      kind?: string;
      payload?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    }
  | {
      _id: string;
      _type: "sitePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      slug?: Slug;
      description?: string;
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      candidate?: CandidateProfileReference;
      download?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      legacyPath?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | {
      _id: string;
      _type: "writingGuidance";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      scope?:
        | "analysis"
        | "answer"
        | "assessment"
        | "brief"
        | "cover"
        | "research"
        | "shared";
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      reviewedAt?: string;
      migration?: Migration;
      sourcePayload?: string;
    }
  | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "analysisSettings" && _id == "fit-analysis-settings"][0]{\n  _id, _rev, texts[]{key, text}, questions[]{key, type, instructions, criteria, options[]{key, text}},\n  dimensions[]{id, label, weight, gap}, facts[]{question, answer}, routineQuestions,\n  personalFacts{availability, location, sponsorship}\n}': ANALYSIS_SETTINGS_QUERY_RESULT;
    '{\n  "analysisSettings": count(*[_type == "analysisSettings"]),\n  "candidateProfile": count(*[_type == "candidateProfile"]),\n  "candidateEvidence": count(*[_type == "candidateEvidence"]),\n  "job": count(*[_type == "job"]),\n  "applicationQuestion": count(*[_type == "applicationQuestion"]),\n  "fitReport": count(*[_type == "fitReport"]),\n  "coverLetter": count(*[_type == "coverLetter"]),\n  "companyResearch": count(*[_type == "companyResearch"]),\n  "interviewBrief": count(*[_type == "interviewBrief"]),\n  "fitAssessment": count(*[_type == "fitAssessment"]),\n  "sitePage": count(*[_type == "sitePage"]),\n  "writingGuidance": count(*[_type == "writingGuidance"])\n}': CONTENT_COUNTS_QUERY_RESULT;
    '*[_type == "candidateProfile" && _id == $id][0]{\n  _id, _rev, name, headline, summary, motivationSummary, interviewSummary,\n  location, availability, workEligibility, noticePeriod, careerDirection,\n  workingPreferences, salaryPreferences, constraints, confirmedAnswers, reviewedAt,\n  evidence[]->{_id, _rev, title, kind, organisation, period, body, sources, reviewedAt}\n}': CANDIDATE_QUERY_RESULT;
    '*[_type == "job" && _id == $id][0]{\n  ...,\n  candidate->{_id, name}, activeReport->, activeCoverLetter->, activeResearch->,\n  activeBrief->, activeAssessment->,\n  "questions": *[_type == "applicationQuestion" && job._ref == ^._id] | order(order asc, _createdAt asc),\n  "reportVersions": *[_type == "fitReport" && (job._ref == ^._id || ^._id in jobs[]._ref)] | order(generatedAt desc){_id, versionId, generatedAt, model, active},\n  "coverVersions": *[_type == "coverLetter" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model},\n  "researchVersions": *[_type == "companyResearch" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model},\n  "briefVersions": *[_type == "interviewBrief" && job._ref == ^._id] | order(generatedAt desc){_id, versionId, generatedAt, model}\n}': JOB_CONTENT_QUERY_RESULT;
    '*[_type == $type] | order(_updatedAt desc, _id asc)[$start...$end]{\n  _id, _type, _rev, _updatedAt, title, name, role, company, question, headline, stage,\n  "slug": slug.current\n}': CONTENT_LIST_QUERY_RESULT;
    "*[_type == $type && _id == $id][0]": CONTENT_DOCUMENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
