// Opportunities from a Gmail scan of 15 Jun to 17 Aug 2026.
//
// Merged from two passes: a deep pass that opened the LinkedIn alert digests
// and pulled out the individual roles inside them (33 roles, with the fit
// scores and rationales), plus a lighter pass that caught the CINC Systems
// approach the first pass missed. 34 roles total.
//
// This is a captured snapshot, not a live integration. The app holds no Gmail
// credentials; the scan runs separately and the result is pasted here, so the
// server never touches an inbox. Import is idempotent and matches on
// externalId first, then Gmail threadId, so re-importing updates the metadata
// on a row while leaving whatever stage and notes you have set alone.
//
// score/tier are a model-generated read of fit against Bernardo's profile,
// weighted location 0.35, AI-or-DX surface 0.35, leadership scope 0.30.
// They are not employer assessments. Tiers: Act now >=80, Worth a look 58-79,
// Background 40-57, Off-target <40.
//
// Known caveat carried over from the source: the Fruition Group alert and
// Josh Maguire's vehicle-rental brief are merged into one row here and may
// actually be two separate briefs. Salary was advertised on only 3 of 33.

export const INBOX_SCAN_META = {
  "window": {
    "from": "2026-06-15",
    "to": "2026-08-17"
  },
  "scannedAt": "2026-08-17",
  "provenance": "Gmail: 3 direct recruiter InMails + 12 LinkedIn alert digests + 1 direct recruiter email",
  "roleCount": 34
};

export const INBOX_OPPORTUNITIES = [
  {
    "externalId": "sanity--software-engineering-manager-web",
    "company": "Sanity",
    "role": "Software Engineering Manager, Web",
    "source": "LinkedIn — you viewed this",
    "sourceType": "viewed",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4432364065",
    "threadId": "",
    "location": "Distributed (Oslo/US)",
    "locationMode": "Remote-friendly",
    "salary": "",
    "score": 95,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 100,
      "aiDx": 95,
      "leadership": 90
    },
    "rationale": "The closest thing to a purpose-built role for you in the whole inbox. You chose Sanity as the target CMS in your Website Platform 2026 Vision — you have already argued their product's case in a platform strategy doc. Web team leadership at a DX company, remote-native.",
    "replyOwed": false,
    "userViewed": true,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "openai--manager-forward-deployed-engineering",
    "company": "OpenAI",
    "role": "Manager, Forward Deployed Engineering",
    "source": "LinkedIn — you viewed this",
    "sourceType": "viewed",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4417178056",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 88,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 65,
      "aiDx": 100,
      "leadership": 100
    },
    "rationale": "You viewed this one too. FDE is orchestrating humans, AI and customers at the same time — your 'orchestrator' framing, as a job description. London is the cost: no longer remote, though a Harrogate-London pattern is doable.",
    "replyOwed": false,
    "userViewed": true,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "cinc-systems--principal-designops-engineer",
    "company": "CINC Systems",
    "role": "Principal DesignOps Engineer",
    "source": "Alex Reeder, Riviera Partners (direct email)",
    "sourceType": "recruiter-email",
    "sourceUrl": "",
    "threadId": "19fa8e8a11fc30ec",
    "location": "Fully remote (worldwide)",
    "locationMode": "Remote-friendly",
    "salary": "",
    "score": 88,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 100,
      "aiDx": 90,
      "leadership": 70
    },
    "rationale": "Design system, component libraries and Figma-to-code pipelines, reporting to the CTO, with the explicit brief of making the whole design pipeline AI-native. That is your CV read back to you. Fully remote worldwide. Alex followed up twice and then soft-closed on 11 Aug, so it needs reviving rather than answering.",
    "replyOwed": true,
    "userViewed": false,
    "recruiter": {
      "name": "Alex Reeder",
      "org": "Riviera Partners",
      "receivedAt": "2026-07-28",
      "daysWaiting": 20
    },
    "receivedAt": "2026-07-28T13:27:21Z",
    "stage": "new",
    "notes": "Three emails: intro 28 Jul, follow-up 4 Aug, soft close 11 Aug (\"if the timing isn't right, that's fine\"). Not replied to. Starred in Gmail.",
    "jobDescription": "Principal DesignOps Engineer at CINC Systems, reporting directly to the CTO.\n\nCINC Systems is a leading SaaS platform powering 50k+ property associations across the US. They are rebuilding their platform from the ground up and need a Principal DesignOps Engineer to own it all: design system, component libraries, Figma-to-code pipelines, and how AI gets woven into the UX. Real ownership, CTO-level visibility.\n\nThe person in this role will own making their entire design pipeline AI-native while the product scales to 14 million users. Suited to someone who enjoys 0 to 1 work in a highly evolving technological environment.\n\nFully remote, can be located anywhere in the world."
  },
  {
    "externalId": "via-digitech-resourcing--software-engineering-team-lead-smart-energy",
    "company": "via DigiTech Resourcing",
    "role": "Software Engineering Team Lead — Smart Energy",
    "source": "Matt Taylor, DigiTech Resourcing (LinkedIn InMail)",
    "sourceType": "recruiter-inmail",
    "sourceUrl": "",
    "threadId": "19ff0195e5009249",
    "location": "Harrogate, 2 days/wk",
    "locationMode": "Yorkshire",
    "salary": "£90–100k",
    "score": 85,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 100,
      "aiDx": 60,
      "leadership": 96
    },
    "rationale": "In your town, two days a week, reporting to the CTO, on React/Node/TypeScript. Best salary-to-life ratio here by a distance. IoT data rather than AI is the one gap. Matt Taylor is waiting on a reply.",
    "replyOwed": true,
    "userViewed": false,
    "recruiter": {
      "name": "Matt Taylor",
      "org": "DigiTech Resourcing",
      "receivedAt": "2026-08-11",
      "daysWaiting": 6
    },
    "receivedAt": "2026-08-11T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": "Software Engineering Team Lead, reporting to the CTO. Harrogate, 2 days per week in the office. Smart energy sector. Salary £90,000 - £100,000.\n\nA smart technology company driving innovation within the energy sector, creating solutions across hardware, software, and cloud services to unlock the power of customer data insights. Reporting to the CTO, you play a key role in the development and release of their products.\n\nYou will lead a high-performing engineering team responsible for building and scaling a B2B SaaS platform that delivers energy insights from IoT devices through a customer-facing portal and real-time data streams. This role combines hands-on technical leadership with people management, ensuring the team delivers reliable, scalable, and secure solutions that turn complex IoT data into actionable intelligence for customers, and provides an end-to-end customer experience.\n\nExperience needed:\n- Bachelor's or master's degree in computer science or related field.\n- Proven experience leading software development teams in a SaaS environment.\n- Strong background in backend development (APIs, microservices, distributed systems).\n- Familiarity with AWS.\n- Solid understanding of system scalability, performance optimization, and security.\n- Experience with Agile/Scrum methodologies.\n- Proven experience leading or mentoring engineering teams.\n- Software development using JavaScript or TypeScript with React and Node.js."
  },
  {
    "externalId": "lightdash--head-of-engineering",
    "company": "Lightdash",
    "role": "Head of Engineering",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4440814828",
    "threadId": "",
    "location": "London Area",
    "locationMode": "Remote-friendly",
    "salary": "",
    "score": 82,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 80,
      "aiDx": 90,
      "leadership": 75
    },
    "rationale": "Open-source BI tooling — developer-experience product, small team, head-of scope. The kind of place where your platform-vision writing is the job rather than a side effect of it.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "ashby--engineering-manager-uk",
    "company": "Ashby",
    "role": "Engineering Manager — UK",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4403607781",
    "threadId": "",
    "location": "London (remote-first co)",
    "locationMode": "Remote-friendly",
    "salary": "",
    "score": 80,
    "tier": "Act now",
    "scoreBreakdown": {
      "location": 85,
      "aiDx": 75,
      "leadership": 80
    },
    "rationale": "Remote-first by construction and known for taking engineering craft seriously. Product-minded EM role at a company whose customers are recruiters — useful context to have sitting in your own search.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "getty-images--head-of-web-unsplash",
    "company": "Getty Images",
    "role": "Head of Web, Unsplash",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4408467284",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 76,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 60,
      "aiDx": 75,
      "leadership": 95
    },
    "rationale": "Literally the surface you ran at SingleStore — a high-traffic web property with SEO as the acquisition channel — but as the whole remit rather than one team's. Getty is the enterprise wrapper around it.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "parloa--manager-forward-deployed-engineering",
    "company": "Parloa",
    "role": "Manager, Forward Deployed Engineering",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4432440811",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 70,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 90,
      "leadership": 65
    },
    "rationale": "AI voice agents, well funded, genuine FDE work. Same shape as the OpenAI role with a shorter queue in front of it.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "cuvva--engineering-manager",
    "company": "Cuvva",
    "role": "Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4433087999",
    "threadId": "",
    "location": "London Area",
    "locationMode": "London",
    "salary": "",
    "score": 68,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 54,
      "leadership": 100
    },
    "rationale": "Mobile-first insurtech with a real product culture. Good EM scope, though the AI/DX angle you want is thin.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "multiverse--senior-engineering-manager",
    "company": "Multiverse",
    "role": "Senior Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4433177625",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 67,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 70,
      "leadership": 78
    },
    "rationale": "AI-and-apprenticeships, senior scope, mission-shaped. The learning-and-development angle rhymes with what you care about outside work.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "hubscale--head-of-forward-deployed-engineering",
    "company": "Hubscale",
    "role": "Head of Forward Deployed Engineering",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4439423092",
    "threadId": "",
    "location": "London Area",
    "locationMode": "London",
    "salary": "",
    "score": 66,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 78,
      "leadership": 65
    },
    "rationale": "Head-of title on an FDE function. Small enough that the role is what you make it; small enough to be a risk.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "kira--engineering-manager-united-kingdom",
    "company": "Kira",
    "role": "Engineering Manager — United Kingdom",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4453524675",
    "threadId": "",
    "location": "London Area",
    "locationMode": "London",
    "salary": "",
    "score": 65,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 77,
      "leadership": 62
    },
    "rationale": "AI product company hiring its UK engineering leadership. Early enough that scope is wide, unproven enough that you'd want to see the funding.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "c3-ai--forward-deployed-team-lead",
    "company": "C3 AI",
    "role": "Forward Deployed Team Lead",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4424336047",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 64,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 80,
      "leadership": 56
    },
    "rationale": "Enterprise AI at scale. Lead rather than manager, and C3's delivery model is consultancy-flavoured — less platform, more deployment.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "via-fruition-group--engineering-manager-frontend-new-platform",
    "company": "via Fruition Group",
    "role": "Engineering Manager (Frontend, new platform)",
    "source": "Josh Maguire, Fruition (LinkedIn InMail)",
    "sourceType": "recruiter-inmail",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4448159703",
    "threadId": "1a00fd55e78c4bdc",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 62,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 85,
      "aiDx": 54,
      "leadership": 45
    },
    "rationale": "UK's largest vehicle rental supplier, brand-new IT estate on React/Node/TS, heavy AI tooling investment, building the culture from zero. Josh Maguire has been waiting since June — worth at least a reply.",
    "replyOwed": true,
    "userViewed": false,
    "recruiter": {
      "name": "Josh Maguire",
      "org": "Fruition",
      "receivedAt": "2026-06-15",
      "daysWaiting": 63
    },
    "receivedAt": "2026-06-15T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "artificial-labs--lead-forward-deployed-engineer",
    "company": "Artificial Labs",
    "role": "Lead Forward Deployed Engineer",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4411354143",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 60,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 78,
      "leadership": 45
    },
    "rationale": "Insurtech AI, lead-level. More hands-on than your last five years — fine if you want to be closer to the keyboard for a stretch.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "via-hunter-bond--software-engineering-manager",
    "company": "via Hunter Bond",
    "role": "Software Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4449822380",
    "threadId": "",
    "location": "London, hybrid",
    "locationMode": "London",
    "salary": "£110k",
    "score": 60,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 58,
      "aiDx": 50,
      "leadership": 74
    },
    "rationale": "Top advertised number in the set and a useful benchmark for what you should be asking. Agency listing, so the actual employer is unknown until you engage.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "disco--engineering-manager",
    "company": "DISCO",
    "role": "Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4448123200",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 58,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 60,
      "leadership": 60
    },
    "rationale": "Legal tech with a serious AI investment. Established company, conventional EM remit.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "premier-farnell-via-linkedin-inmail--ui-engineering-manager",
    "company": "Premier Farnell (via LinkedIn InMail)",
    "role": "UI Engineering Manager",
    "source": "Joe McMahon, agency (LinkedIn InMail)",
    "sourceType": "recruiter-inmail",
    "sourceUrl": "",
    "threadId": "",
    "location": "Leeds, 3 days onsite",
    "locationMode": "Yorkshire",
    "salary": "£75k + 5%",
    "score": 58,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 70,
      "aiDx": 50,
      "leadership": 54
    },
    "rationale": "Three teams, ~19 engineers UK and India, headless replatform at scale, explicit move toward an AI-driven SDLC — the scope genuinely fits. The pay doesn't: £75k is below your level, and 3 days in Leeds is the heaviest commute here. Joe McMahon has been waiting 45 days.",
    "replyOwed": true,
    "userViewed": false,
    "recruiter": {
      "name": "Joe McMahon",
      "org": "(agency, unnamed)",
      "receivedAt": "2026-07-03",
      "daysWaiting": 45
    },
    "receivedAt": "2026-07-03T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "baringa--senior-manager-forward-deployed-ai-engineer",
    "company": "Baringa",
    "role": "Senior Manager, Forward Deployed AI Engineer",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4437044753",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 58,
    "tier": "Worth a look",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 72,
      "leadership": 45
    },
    "rationale": "Consultancy, so client work rather than product ownership. Senior title and real AI exposure if the model suits you.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "perk--engineering-manager-london",
    "company": "Perk",
    "role": "Engineering Manager — London",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4432399691",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 56,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 55,
      "leadership": 58
    },
    "rationale": "Early-stage, so wide remit and real equity. Thin public information — treat as a conversation rather than an application.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "via-gravitas-recruitment--software-engineering-manager-leeds",
    "company": "via Gravitas Recruitment",
    "role": "Software Engineering Manager — Leeds",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4450119879",
    "threadId": "19ffb3c1a237680c",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 55,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 85,
      "aiDx": 34,
      "leadership": 45
    },
    "rationale": "Agency listing with no named employer or salary. Low information — only worth a click to find out who's behind it.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "hackajob--forward-deployed-ai-engineer-senior-manager",
    "company": "hackajob",
    "role": "Forward Deployed AI Engineer, Senior Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4413529640",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 55,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 66,
      "leadership": 42
    },
    "rationale": "Marketplace listing rather than a direct hire. Same FDE shape, one more layer of intermediary.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "accenture-uk-ireland--forward-deployed-eng-director",
    "company": "Accenture UK & Ireland",
    "role": "Forward Deployed Eng Director",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4443892356",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 54,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 60,
      "leadership": 45
    },
    "rationale": "Director scope, but a very large consultancy. Distance from the work would be the thing to test.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "sotheby-s--engineering-manager",
    "company": "Sotheby's",
    "role": "Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4443588150",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 52,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 40,
      "leadership": 62
    },
    "rationale": "Interesting brand, conventional in-house engineering. Little AI or DX surface.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "accenture-uk-ireland--forward-deployed-engineering-manager",
    "company": "Accenture UK & Ireland",
    "role": "Forward Deployed Engineering (Manager)",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4441355780",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 50,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 55,
      "leadership": 38
    },
    "rationale": "The manager-grade version of the Accenture director role. Same caveats, less scope.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "marks-and-spencer--software-engineering-manager",
    "company": "Marks and Spencer",
    "role": "Software Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4450273370",
    "threadId": "",
    "location": "London Area",
    "locationMode": "London",
    "salary": "",
    "score": 50,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 38,
      "leadership": 58
    },
    "rationale": "Large retail eCommerce. Stable and well-resourced; not where AI or developer experience is the point.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "holland-barrett--senior-engineering-manager",
    "company": "Holland & Barrett",
    "role": "Senior Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4448602492",
    "threadId": "",
    "location": "London",
    "locationMode": "London",
    "salary": "",
    "score": 48,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 55,
      "aiDx": 32,
      "leadership": 58
    },
    "rationale": "Retail again, senior title. Furthest from the AI/DX centre of gravity you asked me to weight for.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "yorkshire-building-society--cloud-platform-team-manager",
    "company": "Yorkshire Building Society",
    "role": "Cloud Platform Team Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4447523908",
    "threadId": "",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 42,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 85,
      "aiDx": 14,
      "leadership": 25
    },
    "rationale": "Local and stable, which counts for something. Infrastructure rather than product, and a long way from your frontend/design-systems core.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "createfuture--tech-lead-mobile",
    "company": "CreateFuture",
    "role": "Tech Lead (Mobile)",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4442813361",
    "threadId": "19fd72f801013bda",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 40,
    "tier": "Background",
    "scoreBreakdown": {
      "location": 85,
      "aiDx": 15,
      "leadership": 18
    },
    "rationale": "Mobile-native lead role at a consultancy. You've argued the PWA case over native for years — this is the opposite bet.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "new",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "liberty-blume--senior-engineering-support-manager",
    "company": "Liberty Blume",
    "role": "Senior Engineering Support Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4427374935",
    "threadId": "19fc7bc7570c49d1",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 30,
    "tier": "Off-target",
    "scoreBreakdown": {
      "location": 75,
      "aiDx": 3,
      "leadership": 8
    },
    "rationale": "Support function, not product engineering. Appearing in your alerts because of the job title alone.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "not_a_fit",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "uk-health-security-agency--infrastructure-manager",
    "company": "UK Health Security Agency",
    "role": "Infrastructure Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4451651892",
    "threadId": "",
    "location": "Leeds",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 28,
    "tier": "Off-target",
    "scoreBreakdown": {
      "location": 75,
      "aiDx": 2,
      "leadership": 5
    },
    "rationale": "Public-sector IT infrastructure. Keyword match, not a fit.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "not_a_fit",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "mabey-hire--development-engineering-manager",
    "company": "Mabey Hire",
    "role": "Development Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4447528542",
    "threadId": "",
    "location": "Dewsbury",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 5,
    "tier": "Off-target",
    "scoreBreakdown": {
      "location": 10,
      "aiDx": 0,
      "leadership": 5
    },
    "rationale": "Mechanical engineering, not software. Your alerts are matching on the word 'engineering' — worth tightening the LinkedIn filter.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "not_a_fit",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "teconnex-uk--project-manager",
    "company": "Teconnex UK",
    "role": "Project Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4445895850",
    "threadId": "",
    "location": "Keighley",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 5,
    "tier": "Off-target",
    "scoreBreakdown": {
      "location": 10,
      "aiDx": 0,
      "leadership": 5
    },
    "rationale": "Manufacturing project management. Noise in the alert feed.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "not_a_fit",
    "notes": "",
    "jobDescription": ""
  },
  {
    "externalId": "dawsongroup--hgv-compliance-network-engineering-manager",
    "company": "Dawsongroup",
    "role": "HGV Compliance, Network & Engineering Manager",
    "source": "LinkedIn job alert",
    "sourceType": "job-alert",
    "sourceUrl": "https://www.linkedin.com/jobs/view/4452489812",
    "threadId": "",
    "location": "Brighouse",
    "locationMode": "Yorkshire",
    "salary": "",
    "score": 3,
    "tier": "Off-target",
    "scoreBreakdown": {
      "location": 8,
      "aiDx": 0,
      "leadership": 1
    },
    "rationale": "Heavy goods vehicle compliance. Same keyword-matching problem.",
    "replyOwed": false,
    "userViewed": false,
    "recruiter": null,
    "receivedAt": "2026-08-17T09:00:00Z",
    "stage": "not_a_fit",
    "notes": "",
    "jobDescription": ""
  }
];
